"""
Tamil Nadu Districts Data Module
Covers all 38 districts of Tamil Nadu with geographic coordinates,
population, and initial resource inventory.
"""

from dataclasses import dataclass, field
from typing import Dict, List


@dataclass
class DistrictInfo:
    """Represents a Tamil Nadu district with its resources and metadata."""

    id: str
    name: str
    headquarters: str
    latitude: float
    longitude: float
    population: int
    area_sq_km: float
    resources: Dict[str, int] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "headquarters": self.headquarters,
            "latitude": self.latitude,
            "longitude": self.longitude,
            "population": self.population,
            "area_sq_km": self.area_sq_km,
            "resources": dict(self.resources),
        }


# All 38 districts of Tamil Nadu with approximate coordinates and 2021 census data
TAMIL_NADU_DISTRICTS: List[DistrictInfo] = [
    DistrictInfo(
        id="TN-AR",
        name="Ariyalur",
        headquarters="Ariyalur",
        latitude=11.1404,
        longitude=79.0778,
        population=754894,
        area_sq_km=1949,
        resources={
            "ambulances": 8,
            "fire_trucks": 4,
            "police_units": 12,
            "rescue_teams": 3,
            "medical_kits": 50,
            "food_packets": 500,
            "water_tankers": 5,
        },
    ),
    DistrictInfo(
        id="TN-CGL",
        name="Chengalpattu",
        headquarters="Chengalpattu",
        latitude=12.6921,
        longitude=79.9762,
        population=2556244,
        area_sq_km=2944,
        resources={
            "ambulances": 22,
            "fire_trucks": 11,
            "police_units": 35,
            "rescue_teams": 8,
            "medical_kits": 150,
            "food_packets": 1500,
            "water_tankers": 14,
        },
    ),
    DistrictInfo(
        id="TN-CHE",
        name="Chennai",
        headquarters="Chennai",
        latitude=13.0827,
        longitude=80.2707,
        population=7088000,
        area_sq_km=426,
        resources={
            "ambulances": 80,
            "fire_trucks": 40,
            "police_units": 120,
            "rescue_teams": 30,
            "medical_kits": 500,
            "food_packets": 5000,
            "water_tankers": 50,
        },
    ),
    DistrictInfo(
        id="TN-CBE",
        name="Coimbatore",
        headquarters="Coimbatore",
        latitude=11.0168,
        longitude=76.9558,
        population=3458045,
        area_sq_km=4723,
        resources={
            "ambulances": 35,
            "fire_trucks": 18,
            "police_units": 55,
            "rescue_teams": 14,
            "medical_kits": 220,
            "food_packets": 2200,
            "water_tankers": 22,
        },
    ),
    DistrictInfo(
        id="TN-CUD",
        name="Cuddalore",
        headquarters="Cuddalore",
        latitude=11.7480,
        longitude=79.7714,
        population=2605914,
        area_sq_km=3678,
        resources={
            "ambulances": 24,
            "fire_trucks": 12,
            "police_units": 38,
            "rescue_teams": 9,
            "medical_kits": 160,
            "food_packets": 1600,
            "water_tankers": 16,
        },
    ),
    DistrictInfo(
        id="TN-DHP",
        name="Dharmapuri",
        headquarters="Dharmapuri",
        latitude=12.1277,
        longitude=78.1576,
        population=1506843,
        area_sq_km=4497,
        resources={
            "ambulances": 14,
            "fire_trucks": 7,
            "police_units": 22,
            "rescue_teams": 5,
            "medical_kits": 90,
            "food_packets": 900,
            "water_tankers": 9,
        },
    ),
    DistrictInfo(
        id="TN-DGL",
        name="Dindigul",
        headquarters="Dindigul",
        latitude=10.3624,
        longitude=77.9695,
        population=2159775,
        area_sq_km=6267,
        resources={
            "ambulances": 20,
            "fire_trucks": 10,
            "police_units": 32,
            "rescue_teams": 7,
            "medical_kits": 130,
            "food_packets": 1300,
            "water_tankers": 13,
        },
    ),
    DistrictInfo(
        id="TN-ERD",
        name="Erode",
        headquarters="Erode",
        latitude=11.3410,
        longitude=77.7172,
        population=2251744,
        area_sq_km=5714,
        resources={
            "ambulances": 21,
            "fire_trucks": 10,
            "police_units": 33,
            "rescue_teams": 8,
            "medical_kits": 135,
            "food_packets": 1350,
            "water_tankers": 13,
        },
    ),
    DistrictInfo(
        id="TN-KLK",
        name="Kallakurichi",
        headquarters="Kallakurichi",
        latitude=11.7380,
        longitude=78.9582,
        population=1370281,
        area_sq_km=3521,
        resources={
            "ambulances": 13,
            "fire_trucks": 6,
            "police_units": 20,
            "rescue_teams": 5,
            "medical_kits": 80,
            "food_packets": 800,
            "water_tankers": 8,
        },
    ),
    DistrictInfo(
        id="TN-KPM",
        name="Kancheepuram",
        headquarters="Kancheepuram",
        latitude=12.8185,
        longitude=79.6947,
        population=1166401,
        area_sq_km=1686,
        resources={
            "ambulances": 12,
            "fire_trucks": 6,
            "police_units": 18,
            "rescue_teams": 5,
            "medical_kits": 75,
            "food_packets": 750,
            "water_tankers": 7,
        },
    ),
    DistrictInfo(
        id="TN-KNY",
        name="Kanyakumari",
        headquarters="Nagercoil",
        latitude=8.0883,
        longitude=77.5385,
        population=1870374,
        area_sq_km=1684,
        resources={
            "ambulances": 18,
            "fire_trucks": 9,
            "police_units": 28,
            "rescue_teams": 7,
            "medical_kits": 115,
            "food_packets": 1150,
            "water_tankers": 11,
        },
    ),
    DistrictInfo(
        id="TN-KRR",
        name="Karur",
        headquarters="Karur",
        latitude=10.9601,
        longitude=78.0766,
        population=1064493,
        area_sq_km=2895,
        resources={
            "ambulances": 10,
            "fire_trucks": 5,
            "police_units": 16,
            "rescue_teams": 4,
            "medical_kits": 65,
            "food_packets": 650,
            "water_tankers": 6,
        },
    ),
    DistrictInfo(
        id="TN-KRG",
        name="Krishnagiri",
        headquarters="Krishnagiri",
        latitude=12.5186,
        longitude=78.2137,
        population=1883731,
        area_sq_km=5143,
        resources={
            "ambulances": 18,
            "fire_trucks": 9,
            "police_units": 28,
            "rescue_teams": 7,
            "medical_kits": 115,
            "food_packets": 1150,
            "water_tankers": 11,
        },
    ),
    DistrictInfo(
        id="TN-MDU",
        name="Madurai",
        headquarters="Madurai",
        latitude=9.9252,
        longitude=78.1198,
        population=3038252,
        area_sq_km=3741,
        resources={
            "ambulances": 30,
            "fire_trucks": 15,
            "police_units": 48,
            "rescue_teams": 12,
            "medical_kits": 190,
            "food_packets": 1900,
            "water_tankers": 19,
        },
    ),
    DistrictInfo(
        id="TN-MYD",
        name="Mayiladuthurai",
        headquarters="Mayiladuthurai",
        latitude=11.1015,
        longitude=79.6513,
        population=918356,
        area_sq_km=1553,
        resources={
            "ambulances": 9,
            "fire_trucks": 4,
            "police_units": 14,
            "rescue_teams": 4,
            "medical_kits": 55,
            "food_packets": 550,
            "water_tankers": 5,
        },
    ),
    DistrictInfo(
        id="TN-NGP",
        name="Nagapattinam",
        headquarters="Nagapattinam",
        latitude=10.7672,
        longitude=79.8449,
        population=1614069,
        area_sq_km=2716,
        resources={
            "ambulances": 15,
            "fire_trucks": 7,
            "police_units": 23,
            "rescue_teams": 6,
            "medical_kits": 95,
            "food_packets": 950,
            "water_tankers": 9,
        },
    ),
    DistrictInfo(
        id="TN-NMK",
        name="Namakkal",
        headquarters="Namakkal",
        latitude=11.2189,
        longitude=78.1674,
        population=1726601,
        area_sq_km=3363,
        resources={
            "ambulances": 16,
            "fire_trucks": 8,
            "police_units": 25,
            "rescue_teams": 6,
            "medical_kits": 100,
            "food_packets": 1000,
            "water_tankers": 10,
        },
    ),
    DistrictInfo(
        id="TN-NLG",
        name="Nilgiris",
        headquarters="Ooty",
        latitude=11.4102,
        longitude=76.6950,
        population=735394,
        area_sq_km=2544,
        resources={
            "ambulances": 8,
            "fire_trucks": 4,
            "police_units": 12,
            "rescue_teams": 4,
            "medical_kits": 48,
            "food_packets": 480,
            "water_tankers": 5,
        },
    ),
    DistrictInfo(
        id="TN-PRM",
        name="Perambalur",
        headquarters="Perambalur",
        latitude=11.2338,
        longitude=78.8803,
        population=565223,
        area_sq_km=1752,
        resources={
            "ambulances": 6,
            "fire_trucks": 3,
            "police_units": 9,
            "rescue_teams": 3,
            "medical_kits": 36,
            "food_packets": 360,
            "water_tankers": 4,
        },
    ),
    DistrictInfo(
        id="TN-PDK",
        name="Pudukkottai",
        headquarters="Pudukkottai",
        latitude=10.3797,
        longitude=78.8214,
        population=1618345,
        area_sq_km=4651,
        resources={
            "ambulances": 15,
            "fire_trucks": 7,
            "police_units": 24,
            "rescue_teams": 6,
            "medical_kits": 95,
            "food_packets": 950,
            "water_tankers": 10,
        },
    ),
    DistrictInfo(
        id="TN-RMN",
        name="Ramanathapuram",
        headquarters="Ramanathapuram",
        latitude=9.3762,
        longitude=78.8309,
        population=1353445,
        area_sq_km=4123,
        resources={
            "ambulances": 13,
            "fire_trucks": 6,
            "police_units": 20,
            "rescue_teams": 5,
            "medical_kits": 80,
            "food_packets": 800,
            "water_tankers": 8,
        },
    ),
    DistrictInfo(
        id="TN-RNP",
        name="Ranipet",
        headquarters="Ranipet",
        latitude=12.9224,
        longitude=79.3330,
        population=1210277,
        area_sq_km=2349,
        resources={
            "ambulances": 12,
            "fire_trucks": 6,
            "police_units": 18,
            "rescue_teams": 5,
            "medical_kits": 73,
            "food_packets": 730,
            "water_tankers": 7,
        },
    ),
    DistrictInfo(
        id="TN-SLM",
        name="Salem",
        headquarters="Salem",
        latitude=11.6643,
        longitude=78.1460,
        population=3482056,
        area_sq_km=5237,
        resources={
            "ambulances": 34,
            "fire_trucks": 17,
            "police_units": 54,
            "rescue_teams": 13,
            "medical_kits": 215,
            "food_packets": 2150,
            "water_tankers": 21,
        },
    ),
    DistrictInfo(
        id="TN-SVG",
        name="Sivaganga",
        headquarters="Sivaganga",
        latitude=9.8479,
        longitude=78.4808,
        population=1339101,
        area_sq_km=4189,
        resources={
            "ambulances": 13,
            "fire_trucks": 6,
            "police_units": 20,
            "rescue_teams": 5,
            "medical_kits": 80,
            "food_packets": 800,
            "water_tankers": 8,
        },
    ),
    DistrictInfo(
        id="TN-TNK",
        name="Tenkasi",
        headquarters="Tenkasi",
        latitude=8.9592,
        longitude=77.3152,
        population=1407627,
        area_sq_km=3269,
        resources={
            "ambulances": 13,
            "fire_trucks": 7,
            "police_units": 21,
            "rescue_teams": 5,
            "medical_kits": 85,
            "food_packets": 850,
            "water_tankers": 8,
        },
    ),
    DistrictInfo(
        id="TN-TNJ",
        name="Thanjavur",
        headquarters="Thanjavur",
        latitude=10.7870,
        longitude=79.1378,
        population=2405890,
        area_sq_km=3396,
        resources={
            "ambulances": 23,
            "fire_trucks": 11,
            "police_units": 36,
            "rescue_teams": 9,
            "medical_kits": 145,
            "food_packets": 1450,
            "water_tankers": 14,
        },
    ),
    DistrictInfo(
        id="TN-THN",
        name="Theni",
        headquarters="Theni",
        latitude=10.0104,
        longitude=77.4770,
        population=1243853,
        area_sq_km=3242,
        resources={
            "ambulances": 12,
            "fire_trucks": 6,
            "police_units": 19,
            "rescue_teams": 5,
            "medical_kits": 75,
            "food_packets": 750,
            "water_tankers": 7,
        },
    ),
    DistrictInfo(
        id="TN-TUT",
        name="Thoothukudi",
        headquarters="Thoothukudi",
        latitude=8.7642,
        longitude=78.1348,
        population=1750176,
        area_sq_km=4621,
        resources={
            "ambulances": 16,
            "fire_trucks": 8,
            "police_units": 26,
            "rescue_teams": 6,
            "medical_kits": 105,
            "food_packets": 1050,
            "water_tankers": 10,
        },
    ),
    DistrictInfo(
        id="TN-TRY",
        name="Tiruchirappalli",
        headquarters="Tiruchirappalli",
        latitude=10.7905,
        longitude=78.7047,
        population=2722290,
        area_sq_km=4404,
        resources={
            "ambulances": 26,
            "fire_trucks": 13,
            "police_units": 42,
            "rescue_teams": 11,
            "medical_kits": 165,
            "food_packets": 1650,
            "water_tankers": 16,
        },
    ),
    DistrictInfo(
        id="TN-TNV",
        name="Tirunelveli",
        headquarters="Tirunelveli",
        latitude=8.7139,
        longitude=77.7567,
        population=1665253,
        area_sq_km=6724,
        resources={
            "ambulances": 16,
            "fire_trucks": 8,
            "police_units": 25,
            "rescue_teams": 6,
            "medical_kits": 100,
            "food_packets": 1000,
            "water_tankers": 10,
        },
    ),
    DistrictInfo(
        id="TN-TPR",
        name="Tiruppur",
        headquarters="Tiruppur",
        latitude=11.1085,
        longitude=77.3411,
        population=2479052,
        area_sq_km=5186,
        resources={
            "ambulances": 23,
            "fire_trucks": 12,
            "police_units": 37,
            "rescue_teams": 9,
            "medical_kits": 150,
            "food_packets": 1500,
            "water_tankers": 15,
        },
    ),
    DistrictInfo(
        id="TN-TVL",
        name="Tiruvallur",
        headquarters="Tiruvallur",
        latitude=13.1430,
        longitude=79.9098,
        population=3728104,
        area_sq_km=3422,
        resources={
            "ambulances": 35,
            "fire_trucks": 18,
            "police_units": 56,
            "rescue_teams": 14,
            "medical_kits": 225,
            "food_packets": 2250,
            "water_tankers": 22,
        },
    ),
    DistrictInfo(
        id="TN-TVN",
        name="Tiruvannamalai",
        headquarters="Tiruvannamalai",
        latitude=12.2253,
        longitude=79.0747,
        population=2464875,
        area_sq_km=6188,
        resources={
            "ambulances": 23,
            "fire_trucks": 11,
            "police_units": 36,
            "rescue_teams": 9,
            "medical_kits": 148,
            "food_packets": 1480,
            "water_tankers": 15,
        },
    ),
    DistrictInfo(
        id="TN-TVR",
        name="Tiruvarur",
        headquarters="Tiruvarur",
        latitude=10.7730,
        longitude=79.6367,
        population=1264277,
        area_sq_km=2162,
        resources={
            "ambulances": 12,
            "fire_trucks": 6,
            "police_units": 19,
            "rescue_teams": 5,
            "medical_kits": 76,
            "food_packets": 760,
            "water_tankers": 7,
        },
    ),
    DistrictInfo(
        id="TN-TPT",
        name="Tirupattur",
        headquarters="Tirupattur",
        latitude=12.4959,
        longitude=78.5730,
        population=1111812,
        area_sq_km=2663,
        resources={
            "ambulances": 11,
            "fire_trucks": 5,
            "police_units": 17,
            "rescue_teams": 4,
            "medical_kits": 67,
            "food_packets": 670,
            "water_tankers": 7,
        },
    ),
    DistrictInfo(
        id="TN-VLR",
        name="Vellore",
        headquarters="Vellore",
        latitude=12.9165,
        longitude=79.1325,
        population=1614242,
        area_sq_km=2637,
        resources={
            "ambulances": 15,
            "fire_trucks": 7,
            "police_units": 24,
            "rescue_teams": 6,
            "medical_kits": 97,
            "food_packets": 970,
            "water_tankers": 9,
        },
    ),
    DistrictInfo(
        id="TN-VPM",
        name="Villupuram",
        headquarters="Villupuram",
        latitude=11.9401,
        longitude=79.4861,
        population=2093003,
        area_sq_km=7221,
        resources={
            "ambulances": 19,
            "fire_trucks": 10,
            "police_units": 30,
            "rescue_teams": 7,
            "medical_kits": 125,
            "food_packets": 1250,
            "water_tankers": 12,
        },
    ),
    DistrictInfo(
        id="TN-VDN",
        name="Virudhunagar",
        headquarters="Virudhunagar",
        latitude=9.5851,
        longitude=77.9629,
        population=1942288,
        area_sq_km=4283,
        resources={
            "ambulances": 18,
            "fire_trucks": 9,
            "police_units": 29,
            "rescue_teams": 7,
            "medical_kits": 117,
            "food_packets": 1170,
            "water_tankers": 11,
        },
    ),
]

# Build fast lookup by district ID and name
DISTRICTS_BY_ID: Dict[str, DistrictInfo] = {d.id: d for d in TAMIL_NADU_DISTRICTS}
DISTRICTS_BY_NAME: Dict[str, DistrictInfo] = {d.name.lower(): d for d in TAMIL_NADU_DISTRICTS}

TOTAL_DISTRICTS = len(TAMIL_NADU_DISTRICTS)  # 38


def get_district(district_id: str) -> DistrictInfo:
    """Return district info by ID, or raise KeyError if not found."""
    if district_id not in DISTRICTS_BY_ID:
        raise KeyError(f"District '{district_id}' not found")
    return DISTRICTS_BY_ID[district_id]


def get_district_by_name(name: str) -> DistrictInfo:
    """Return district info by name (case-insensitive), or raise KeyError."""
    key = name.lower()
    if key not in DISTRICTS_BY_NAME:
        raise KeyError(f"District '{name}' not found")
    return DISTRICTS_BY_NAME[key]


def list_districts() -> List[dict]:
    """Return a list of all districts as dicts."""
    return [d.to_dict() for d in TAMIL_NADU_DISTRICTS]
